### ISSUE TITLE
Gegen Hindernis fahren

### ISSUE THREAD

**Issue by TimoKramer** [TimoKramer/PatFra#11]
Wenn der C gegen ein Hindernis fährt, hat er ein Leben weniger und muss von der Stelle noch mal beginnen.

**Comment by freudenb** [comment]
Spieler wird jetzt bei Kollsion auf die mitte der Straße gesetzt. Ist das so ok, was meinst du?

**Comment by TimoKramer** [comment]
ich denke das ist ok.
