### ISSUE TITLE
Ziel erreicht

### ISSUE THREAD

**Issue by TimoKramer** [TimoKramer/PatFra#14]
Wenn der Spieler das Ziel erreicht, wird das Spiel angehalten, die Punkte in die DB geschrieben und das Menü angezeigt

**Comment by TimoKramer** [comment]
soll ich das jetzt mit sqlite oder xml oder json lösen? SQLite hätten wir noch das Argument, dass es als DB gilt, oder?

**Comment by freudenb** [comment]
Ich persönlich mag ja JSON mehr als XML. Eine Datenbank brauchten wir ja nicht unbedingt zu benutzen. Also eher XML oder JSON,  ich richt mich da nach dir.
