### ISSUE TITLE
Treffer in Nicht-Abonnenten-Briefkasten

### ISSUE THREAD

**Issue by TimoKramer** [TimoKramer/PatFra#17]
Wenn der Spieler in einen Briefkasten trifft,
wenn der Briefkasten einem Nicht-Abonnenten gehört,
dann passiert nichts.

**Comment by freudenb** [comment]
Woran lassen wir den Spieler erkenne welcher Briefkasten ein Abonnenten Breifkasten ist und welcher nicht? Farbe?

**Comment by TimoKramer** [comment]
Hmm...gute Frage. Im Spiel sind die Häuser von nicht-Abonnenten mit Hunden oder Schussanlagen, also irgendwie 'feindlich'. Ich schlage vor, wir nehmen verschiedene Farben für den Anfang.
