### ISSUE TITLE
Highscore-Liste

### ISSUE THREAD

**Issue by TimoKramer** [TimoKramer/PatFra#18]
Wenn der Spieler im Hauptmenü auf Highscore klickt,
dann wird die Highscore liste angezeigt.

**Comment by TimoKramer** [comment]
Es wird jetzt eine Highscore-Liste nach Spielende dargestellt. Sie ist nicht besonders schön. Meinst du, das sollte mit Table/Skins und so gemacht werden? Ich habe das nicht hingekriegt.
Oder ist Text ok?

**Comment by freudenb** [comment]
Mit Text solltes schon reichen. WIr suchen am besten noch eine passende Font raus zum Spiel passend. Ansonsten würde ich die | Striche noch entfernen und die Zeit angabe find ich unnötig.
Farbe, passende Font und vielleicht noch eine Hintergrundgrafik oder Effekt sollte reichen.

**Comment by freudenb** [comment]
Der Highscore müsste noch nach den Schwierigkeitsmodi unterschieden werden (easy, normal, hard). Den aktuell eingestellten Mode kannst du in der GameScreen Klasse über difficulty.getCurrentMode() abfragen. Reicht ja wenn einfach drei Json-Dateien angelegt werden den Modis entsprechend.
