### ISSUE TITLE
Options-Menü

### ISSUE THREAD

**Issue by TimoKramer** [TimoKramer/PatFra#20]
Wenn sich der Spieler im Startmenü befindet,
wenn der Spieler auf Options klickt,
dann wechselt die Ansicht in den Options-Screen.

**Comment by freudenb** [comment]
Einstellungen für: 
Auflösung
Lautstärke

Optional:
Tastenbelegung
Controller-Unterstützung vielleicht!?

**Comment by TimoKramer** [comment]
ok
