### ISSUE TITLE
erfolgreicher Login

### ISSUE THREAD

**Issue by TimoKramer** [TimoKramer/PatFra#30]
Wenn der Spieler im Login-Menü ist,
wenn der Spieler einen existierenden Namen wählt,
wenn der Spieler 'OK' klickt,
dann ist er eingeloggt.

**Comment by TimoKramer** [comment]
Ich würde es ohne Logins machen, so wie auf Konsolen, dass einfach ein Name gewählt wird.

**Comment by freudenb** [comment]
Login find ich auch unnötig. Würde sagen es reicht schon wenn der Spieler im Highscore Menu, falls er genug Punkte hat um in die Highscoretabelle eingetragen zu werden, sein Name eingibt oder sogar nur die ersten 3 Buchstagen

**Comment by TimoKramer** [comment]
ok, einfach ist gut...dann ist unsere Datenbankanwendung das Speichern der Highscores?!?

**Comment by freudenb** [comment]
Ja,  das sollte das einzige sein, wäre dann nur eine Tabelle
