### ISSUE TITLE
Schwierigkeitsgrad auswählen

### ISSUE THREAD

**Issue by TimoKramer** [TimoKramer/PatFra#32]
Wenn sich der Spieler im Startmenü befindet,
wenn der Spieler einen Schwierigkeitsgrad anklickt, 
dann wird der Schwierigkeitsgrad als Auswahl gespeichert.

**Comment by TimoKramer** [comment]
eigenes Menü, oder im Startmenü integriert?

**Comment by freudenb** [comment]
Ich wär eigentlich eher dafür die Levels zu generieren und dann durch den gewählten Schwierigkeitsgrad die Häufigkeit von Hindernissen und Briefkästen usw. anzupassen. So brauchen wir nicht erst eins zu bauen auch nichts speichern. Die objekte werden dann bevor sie am oberen rand des bildschirms sichtbar sind erstellt. 

Man könnte einfach festlegen das ein Hinderniss eine bestimmte Zahl an festen Orten hat wo es auftauchen kann und dann wird einfach eine Zufallszahl generiert die dann bestimmt an welchen Ort es erstellt wird. 

Der Ort würde sich dann nur in der X-Koordinate ändern, die Y-Koordinate richtet sich immer danach wo der Spieler sich befindet. So könnte man  je nachdem wie viel vom Level sichtbar ist, dass Objekt mit einen bestimmten Abstand zum Spieler erstellen. 
Y-Koordinate des Objekts = Y-Koordinate des Spielers + Festgelegter Abstand

**Comment by TimoKramer** [comment]
Ja klar, das hört sich gut an. Also wählt man im Startmenü Schwierigkeitsgrad und nichts weiter.

**Comment by freudenb** [comment]
Hauptmenü -> Spiel starten -> Schwierigkeitsgrad wählen -> spielen

würd ich sagen
