### ISSUE TITLE
HUD - Leben, Zeitungen, Punkte

### ISSUE THREAD

**Issue by freudenb** [TimoKramer/PatFra#40]
Wenn das Spiel läuft,
soll oben links in der Ecke eine Anzeige zu sehen sein,
für Leben, Zeitungen und Punkte des Spielers

**Comment by TimoKramer** [comment]
Ich habe das HUD und die Statusüberwachung soweit eingebaut. Ich habe aber Probleme, nur einmal einen Event zu feuern, wenn es viele Objekte gibt, wie z.B. bei Paper - Mailbox oder Paper - House. Hast du einen Vorschlag?

**Comment by freudenb** [comment]
Sobald eine Paper mit etwas kollidiert ist kann man sie aus der GameWorld entfernen. Die Mailbox kannste auf full setzen und dann abfragen ob er schon voll ist. 

Zum entfernen von Objekten aus der GameWorld gibts halt noch keine Methoden. Wollt ich noch hinzufügen. 

Wenn man eine weile spielt und hunderte Zeitungen abgeworfen hat ruckelt das Spiel, die Zahl der Zeitungen in der GameWorld muss auf jedenfall eingeschränkt werden.

**Comment by TimoKramer** [comment]
Hier habe ich noch was interessantes gefunden: https://gamedev.stackexchange.com/questions/100886/libgdx-destroy-object-when-not-used
