### ISSUE TITLE
Geschwindigkeit verringern

### ISSUE THREAD

**Issue by TimoKramer** [TimoKramer/PatFra#6]
Wenn der Spieler Pfeil rückwärts drückt, 
dann wird der C langsamer bis die Minimalgeschwindigkeit erreicht ist.

**Comment by freudenb** [comment]
Der C soll jedoch nicht anhalten können, das Spiel bewegt ihn automatisch auf einer bestimmten minimal Geschwindigkeit

**Comment by TimoKramer** [comment]
richtig...
